name: Build STTPortable (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure build output folder exists
        shell: powershell
        run: |
          $buildPath = "STTPortable\\build"
          if (!(Test-Path $buildPath)) { New-Item -ItemType Directory -Path $buildPath | Out-Null }

      - name: Setup AutoHotkey compiler
        shell: powershell
        run: |
          # Fetch AutoHotkey's portable release instead of using Chocolatey.
          $zipUrl = "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.18/AutoHotkey_2.0.18.zip"
          $zipPath = Join-Path $env:TEMP "AutoHotkey_2.0.18.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath
          $destination = "C:\\autohotkey"
          if (Test-Path $destination) {
            Remove-Item $destination -Recurse -Force
          }
          Expand-Archive -Path $zipPath -DestinationPath $destination -Force
          $installerScript = Join-Path $destination "UX\\install-ahk2exe.ahk"
          $ahkExe = Join-Path $destination "AutoHotkey64.exe"
          if (Test-Path $installerScript -and Test-Path $ahkExe) {
            Start-Process -FilePath $ahkExe -ArgumentList $installerScript -Wait -NoNewWindow
          }
          $compiler = "C:\\autohotkey\\Compiler\\Ahk2Exe.exe"
          if (!(Test-Path $compiler)) {
            throw "Ahk2Exe not found at $compiler"
          }

      - name: Compile AHK -> EXE
        shell: powershell
        run: |
          $compiler = "C:\\autohotkey\\Compiler\\Ahk2Exe.exe"
          $src = "STTPortable\\src\\TalkPaste.ahk"
          $out = "STTPortable\\build\\TalkPaste.exe"
          & $compiler /in $src /out $out
          if (!(Test-Path $out)) {
            throw "Compilation failed: $out not found."
          }

      - name: Create ZIP artifact
        shell: powershell
        run: |
          Compress-Archive -Path "STTPortable\\build\\TalkPaste.exe" -DestinationPath "STTPortable\\build\\TalkPaste.zip" -Force

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: TalkPaste.exe
          path: STTPortable/build/TalkPaste.exe
          if-no-files-found: error
          compression-level: 0

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: TalkPaste.zip
          path: STTPortable/build/TalkPaste.zip
          if-no-files-found: error
