name: Build STTPortable (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install AutoHotkey + compiler from Chocolatey
      - name: Install AutoHotkey and Compiler via Chocolatey
        shell: powershell
        run: |
          choco install autohotkey.portable -y
          choco install ahk2exe.portable -y
          $compiler = "C:\ProgramData\chocolatey\lib\ahk2exe.portable\tools\Ahk2Exe.exe"
          if (!(Test-Path $compiler)) {
            Write-Error "Ahk2Exe compiler not found at $compiler"
            exit 1
          }
          "$compiler" | Out-File "$env:RUNNER_TEMP\compiler.txt"
          Write-Host "Ahk2Exe compiler installed successfully."

      # Compile using whatever compiler path Chocolatey provided
      - name: Compile TalkPaste.ahk → TalkPaste.exe
        shell: powershell
        run: |
          $compiler = Get-Content "$env:RUNNER_TEMP\compiler.txt"
          $src = ".\src\TalkPaste.ahk"
          $out = ".\build\TalkPaste.exe"
          if (!(Test-Path ".\build")) { New-Item -ItemType Directory -Path ".\build" | Out-Null }
          & $compiler /in $src /out $out
          if (!(Test-Path $out)) { Write-Error "Compilation failed: TalkPaste.exe not found." ; exit 1 }
          Write-Host "Compilation complete: $out"

      - name: Create ZIP artifact
        shell: powershell
        run: Compress-Archive -Path ".\build\TalkPaste.exe" -DestinationPath ".\build\TalkPaste.zip" -Force

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: TalkPaste.exe
          path: build/TalkPaste.exe
          if-no-files-found: error
          compression-level: 0

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: TalkPaste.zip
          path: build/TalkPaste.zip
          if-no-files-found: error
