name: Build STTPortable (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download AutoHotkey Portable
        shell: powershell
        run: |
          Write-Host "Downloading AutoHotkey v2 portable ZIP..."
          $zipUrl = "https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.18/AutoHotkey_2.0.18.zip"
          $zipPath = "autohotkey.zip"
          $extractDir = "C:\autohotkey"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force
          if (!(Test-Path "$extractDir\Compiler\Ahk2Exe.exe")) {
              Write-Error "Ahk2Exe compiler not found after extraction."
              exit 1
          }
          Write-Host "AutoHotkey extracted successfully."

      - name: Compile AHK → EXE
        shell: powershell
        run: |
          Write-Host "Compiling TalkPaste.ahk to TalkPaste.exe..."
          $compiler = "C:\autohotkey\Compiler\Ahk2Exe.exe"
          & $compiler /in ".\src\TalkPaste.ahk" /out ".\build\TalkPaste.exe"
          if (!(Test-Path ".\build\TalkPaste.exe")) {
              Write-Error "Compilation failed: TalkPaste.exe not found."
              exit 1
          }
          Write-Host "Compilation complete."

      - name: Create ZIP artifact
        shell: powershell
        run: |
          Compress-Archive -Path ".\build\TalkPaste.exe" -DestinationPath ".\build\TalkPaste.zip" -Force
          Write-Host "Created TalkPaste.zip artifact."

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: TalkPaste.exe
          path: build/TalkPaste.exe
          if-no-files-found: error
          compression-level: 0

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: TalkPaste.zip
          path: build/TalkPaste.zip
          if-no-files-found: error
